name: GitHub Actions Testing
on: [workflow_dispatch , push]
    

jobs: 
  First_Job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4   

    - name: Test
      run: echo "Testing new job"

    - name:  cowsay test
      run: /bin/bash cowsay.sh
