name: GitHub Actions Testing
on: 
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
    

jobs: 
  First_Job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4   

    - name: Test
      run: echo "Testing new job"

    - name:  cowsay testing
      run: /bin/bash cowsay.sh
